<?php
echo "<!DOCTYPE html>\n"; 
echo "<html>\n"; 
echo "  <head>\n"; 
echo "    <meta name=\"viewport\" content=\"initial-scale=1.0, user-scalable=no\">\n"; 
echo "    <meta charset=\"utf-8\">\n"; 
echo "    <link href='https://fonts.googleapis.com/css?family=Slabo+27px|Lato' rel='stylesheet' type='text/css'>\n"; 
echo "    <link rel=\"stylesheet\" href=\"css/style.css\">\n"; 
echo "    <script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js\"></script>\n"; 
echo "    <script src=\"js/place_search.js\"></script>\n"; 
echo "    <script src = \"http://plus.google.com/js/client:platform.js\" async defer></script>\n"; 
echo "    <script src=\"https://apis.google.com/js/client.js\" async defer></script>\n"; 
echo "    \n"; 
echo "    <script src=\"jq_chart/js/jquery.mousewheel.js\" type=\"text/javascript\"></script>\n"; 
echo "    <script src=\"jq_chart/js/jquery.jqChart.min.js\" type=\"text/javascript\"></script>\n"; 
echo "    <script src=\"jq_chart/js/jquery.jqRangeSlider.min.js\" type=\"text/javascript\"></script>\n"; 
echo "    <script src=\"js/app_script.js\"></script>\n"; 
echo "\n"; 
echo "    <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyAPOZ8eYlJ-hVhVd5Ye977pQte5NG7xz7s&libraries=places&callback=initAutocomplete&signed_in=true&libraries=places,visualization\"\n"; 
echo "    async defer></script>\n"; 
echo "    <title>One Touch</title>\n"; 
echo "  </head>\n"; 
echo "  <body>\n"; 
echo "   \n"; 
echo "      <div id=\"back_btn\"><</div>\n"; 
echo "      <div id=\"lines\"></div>\n"; 
echo "     <nav class=\"nav-option\">\n"; 
echo "      <ul>\n"; 
echo "       <li> \n"; 
echo "          <button id=\"mail_box\" class=\"g-signin\"\n"; 
echo "            data-scope=\"email\"\n"; 
echo "            data-clientid=\"138230497832-e524d5qpd4tkgl45g27nct1j1gb651oc.apps.googleusercontent.com\"\n"; 
echo "            data-callback=\"onSignInCallback\"\n"; 
echo "            data-theme=\"dark\"\n"; 
echo "            data-cookiepolicy=\"single_host_origin\">\n"; 
echo "            Sign In\n"; 
echo "        </button></li>\n"; 
echo "        <li id=\"back_to_main\"><a href=\"javascript:void(0)\">< Back to Main</a></li>\n"; 
echo "        <li><a href=\"javascript:void(0)\" id=\"profile_details\">My Profile</a></li>\n"; 
echo "        <li><a href=\"javascript:void(0)\" id=\"location_access\">Search</a></li>\n"; 
echo "        <li><a href=\"javascript:void(0)\" id=\"check_mail\">Mail</a></li>\n"; 
echo "        <li><a href=\"javascript:void(0)\" id=\"weather_report\">Weather Forecast</a></li>\n"; 
echo "        <!-- <li><a id=\"fb-login\" href=\"#\"></a></li> -->\n"; 
echo "        <li class=\"facebook_img\">\n"; 
echo "          <a id=\"facebook_profile\" target=\"_blank\" href=\"#\"><img src=\"image/fb.ico\" width=\"32px\" height=\"30px\" alt=\"Direct redirect to your profile\"></a></li>\n"; 
echo "           <span\n"; 
echo "            class=\"fb-like\"\n"; 
echo "            data-share=\"false\"\n"; 
echo "            data-width=\"240\"\n"; 
echo "            data-show-faces=\"true\"\n"; 
echo "            id=\"fb_like_btn\">\n"; 
echo "          </span>\n"; 
echo "\n"; 
echo "        <span id=\"current_time\"></span>\n"; 
echo "        <span id=\"city\"></span>\n"; 
echo "        <a href=\"#\" target=\"_blank\" id=\"user_name\"></a>\n"; 
echo "      </ul>\n"; 
echo "     </nav>\n"; 
echo "      <aside class=\"up_\">\n"; 
echo "        <ul id=\"Location_name\"></ul>\n"; 
echo "      </aside>\n"; 
echo "      \n"; 
echo "      <div class=\"mail_popup\">\n"; 
echo "          <div class=\"detail_header\">\n"; 
echo "           <span></span><span>Email Snippet</span>\n"; 
echo "           <button id=\"close\">X</button>\n"; 
echo "          </div>\n"; 
echo "          <!-- <div class=\"drop_down_option_label\">\n"; 
echo "            <select id=\"label_list\"></select>\n"; 
echo "          </div> -->\n"; 
echo "          <div class=\"mail_box_over_popup\">\n"; 
echo "            <ul class=\"mail_list_container\" id=\"mail_container\"></ul>\n"; 
echo "          </div>\n"; 
echo "      </div>\n"; 
echo "\n"; 
echo "      <div class=\"profile_details_popup popup_profile\">\n"; 
echo "          <div class=\"detail_header\">\n"; 
echo "           <a href=\"#\" target=\"_blank\" id=\"name\"></a>\n"; 
echo "           <button id=\"close\">X</button>\n"; 
echo "          </div>\n"; 
echo "\n"; 
echo "          <div class=\"detail-section\">\n"; 
echo "            <span class=\"profile-img\">\n"; 
echo "              <img src=\"#\" id=\"img_profile\" width=\"120px\" height=\"120px;\">\n"; 
echo "            </span>\n"; 
echo "            <span class=\"user_profile_data\">\n"; 
echo "            <ul>\n"; 
echo "              <li>User's ID :   <span id=\"profile_id\"></span></li>\n"; 
echo "              <li>Gender :   <span id=\"gender\"></span></li>\n"; 
echo "              <li>Email Address :   <span id=\"email\"></span></li>\n"; 
echo "            </ul>\n"; 
echo "            </span>\n"; 
echo "          </div>\n"; 
echo "      </div>\n"; 
echo "\n"; 
echo "      <div class=\"weather-forecast\">\n"; 
echo "        <button class=\"close\" id=\"close\">X</button>\n"; 
echo "        <div class=\"toggle_btn\">\n"; 
echo "          <span id=\"weather_status\" class=\"active\"> Weather Status </span>\n"; 
echo "          <span id=\"weather_forecast\"> Weather Forecast </span>\n"; 
echo "        </div>\n"; 
echo "        <div class=\"weather_casting\">\n"; 
echo "          <div class=\"city-weather\"><h2 class=\"weather-head\" id=\"city_name\"></h2></div>\n"; 
echo "          <div class=\"city-humidity\">Humidity : <h2 class=\"weather-head\" id=\"city_humid\"></h2><sup>%</sup></div>\n"; 
echo "          <div class=\"city-temp\">Temperature : <h2 class=\"weather-head\" id=\"city_temp\"></h2><sup>o</sup>C</div>\n"; 
echo "          <div class=\"city-status\">Current Status : <h2 class=\"weather-head\" id=\"city_status\"></h2></div>\n"; 
echo "          <img src=\"#\" id=\"weather_img\" class=\"weather-icon\" alt=\"weather\">\n"; 
echo "        </div>\n"; 
echo "        <div class=\"weather_forecasting\">\n"; 
echo "            Next 7 days Weather Forecasting\n"; 
echo "            <div class=\"forecast-details\">\n"; 
echo "              <div id=\"jqChart\" style=\"width: 570px; height: 300px;\"></div>\n"; 
echo "             <ul id=\"forecast_data\"></ul>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "      </div>\n"; 
echo "\n"; 
echo "      <input id=\"pac-input\" class=\"controls\" type=\"text\" placeholder=\"Search Box\">\n"; 
echo "      <select id=\"resturant-input\" class=\"controls\">\n"; 
echo "        <option>--- Select ---</option>\n"; 
echo "      </select>\n"; 
echo "    \n"; 
echo "\n"; 
echo "      <div id=\"place_details\"></div>\n"; 
echo "      <div id=\"map2\"></div>\n"; 
echo "        <div id=\"map\"></div>\n"; 
echo "       <div class=\"overlay\"></div>\n"; 
echo "  </body>\n"; 
echo "  \n"; 
echo "\n"; 
echo "</html>\n";
?>